### ISSUE TITLE
Photo for display on index page

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#1]
Are there specs for this photo? George will have designer come up with something.
From: https://github.com/Beth-Mardutho/hugoye-data/issues/3

**Comment by wsalesky** [comment]
@jedwardwalters @gkiraz The specs that work best for the banner image are 1250 x 250 px with at least 180 px/inch resolution.

**Comment by jedwardwalters** [comment]
Sorry I jumped the gun and put all the issues in the wrong place. Thanks for moving them!

**Comment by wsalesky** [comment]
No problem, I didn't have issues enabled on the other repository yet anyway!

**Comment by jedwardwalters** [comment]
I think this is all straightened out now. Closing.
