### ISSUE TITLE
Sponsers

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#10]
@gkiraz @jedwardwalters Does Hugoye need a list of sponsors? (See the bottom of the home page : http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/index.html) If so can one of you fill this page out, or send me the necessary information. 

Thanks!

**Comment by gkiraz** [comment]
We need to acknowledge the Srophe platform (so keep that logo) and if Texas will end-up hosting, then we need their logo as a host. Above the Logos, something like:
_Hugoye: Journal of Syriac Studies_ is built on the Srophe platform and is hosted by <Vanderbilt> with a mirror on <Texas>.

**Comment by wsalesky** [comment]
Updated. (Not on dev due to scheduled webhooks downtime)
