### ISSUE TITLE
Article display

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#16]
Based on @jedwardwalters mockup.

**Comment by jedwardwalters** [comment]
@wsalesky This is a great first draft. I only looked at it quickly because I'm prepping for courses. I have some questions for you about the best way to do various things, so I'll come back later and try to work through some of those.

**Comment by wsalesky** [comment]
Sounds good. We will have to talk about URI's and how we want the links to the articles to look as well.

**Comment by jedwardwalters** [comment]
Yes, I wanted to ask you about the URIs, so I'll make sure that's on the list.

**Comment by wsalesky** [comment]
@jedwardwalters Closing. Please open individual issues for specific changes.
