### ISSUE TITLE
Browse options

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#18]
Browse options:
By Volume, by Author.

**Comment by wsalesky** [comment]
@jedwardwalters see: 
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/authors.html
and
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/volumes.html

Does not look so interesting with only one item, but that is self correcting.

**Comment by jedwardwalters** [comment]
I really like the collapsable aspect. Great idea!

**Comment by wsalesky** [comment]
Closing. We can open new issues for anything that crops up when more items are added.
