### ISSUE TITLE
URIs

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#21]
@wsalesky What are your thoughts on the URIs? 

I realized that I actually made a mistake in the sample one I gave you. I meant to put h21n1brock instead of h21v1n1brock. The "h21n1" stands for Hugoye Vol. 21, number 1, by the way. 

Is this an okay way to do URIs?

**Comment by wsalesky** [comment]
@jedwardwalters that is fine.

**Comment by jedwardwalters** [comment]
Okay. Thanks! I'll go ahead and close this, and I'll update the file name when I edit the notes.
