### ISSUE TITLE
Syriaca URIs and Links

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#22]
I'm trying to think through the best way to employ Syriaca person, place, work records in Hugoye, but there are a few things that I'm not sure about. Let me try to put a few thoughts out here and get your reaction:
1) I assume there's some value in tagging every person/place/work etc that has a syriaca.org URI, particularly for being able to search across the Hugoye corpus?
2) However, I'm not sure I want every single instance of a person's name to be highlighted as a link. I'm imagining reading an article about Ephrem where the name Ephrem appears a lot, and it might be a bit annoying to have that name hyperlinked every time it appears.
3) I think it would be great to incorporate an API from either e-GEDSH or from syriaca.org, but again, I'm not sure about the aesthetics of linking every single occurrence of a name/place, etc. 

One thought I had to try to prevent a million hyperlinks in every article was simply to have a box on the right hand side that displays all of the Syriaca people/places, etc, that are mentioned in the article. And the links could be there.

I suppose I'm thinking through best practices regarding linking data, and I don't really know all the answers. Any thoughts?

**Comment by wsalesky** [comment]
@jedwardwalters That is the way we do it for e-gedsh, so it makes sense to me. I think in e-gedsh they are actually all tagged, but if you wanted to add them as tei:keywords (in the header) or tei:relation elements either of those would work as well. You could check with Dave or Dan to see what makes the most sense with the Srophe data model.

**Comment by jedwardwalters** [comment]
Okay. I do think it makes sense to tag them all. We can talk about aesthetics later.

In terms of functionality, assuming that e-GEDSH is available in time, I'd love to be able to use an API for a pop-up box.

**Comment by wsalesky** [comment]
Sure. Lets get the data how you want it and then work on the display.

**Comment by jedwardwalters** [comment]
Closing this because we will have broader conversation about LOD box.
