### ISSUE TITLE
Footnote references

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#24]
Do you have any preferences on your end for how the notes are displayed in TEI? There are obviously multiple ways to do notes, and it seems that some people prefer the "inline" style of notes rather than listed at the end as I have them in the sample.

One interesting factor to consider here: if I run a word document through Ox Garage for automatic conversion into TEI format, it renders the footnote in the inline style of notes rather than the linked reference system I used in the sample. So, that's one thing to consider since I'll have a lot of articles from past issues to convert. 

At any rate, I just wondered if there was a particular way of doing notes in TEI that would be better on your end.

And, a related issue: could we get a pop up box to display the content of the note when the footnote reference number is clicked rather than moving to the bottom of the page?

**Comment by jedwardwalters** [comment]
@wsalesky Follow up: It seems like the inline style of notes is far more common these days. Essentially it would be a note tag with a type="footnote" element and a n="" element for the note number. Then the content of the note would be displayed in a p tag inside the note tag (as opposed to simply linking to the content at the end). So, since this seems to be the preferred method and it will make things easier on the conversion of old issues through Ox Garage, I'm going to go ahead and convert our test article.

**Comment by wsalesky** [comment]
That works for me. Do you want all the notes to appear in a notes section at the bottom of the article, as well as in a popup when you click the footnote number?

**Comment by jedwardwalters** [comment]
Yes, I do think they should also appear at the bottom in addition to the popup. Thanks.

**Comment by jedwardwalters** [comment]
I'll try to get the note format updated ASAP.

**Comment by wsalesky** [comment]
@jedwardwalters let me know when you have this ready and I will amend the code.

**Comment by wsalesky** [comment]
@jedwardwalters Thanks for the reminder, you caught me just before I shut off the computer! How does this look: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/record.html?id=https://hugoye.org/h21v1n1brock

**Comment by jedwardwalters** [comment]
Something is off with the pop up display. You can see it here in this screenshot. The text is displaying, but there's no box. The notes at the bottom of the page look fine.
<img width="1440" alt="screen shot 2018-04-07 at 10 27 10 pm" src="https://user-images.githubusercontent.com/11543800/38462321-0fa04ede-3ab3-11e8-8cd2-5433bac8f26f.png">

**Comment by wsalesky** [comment]
Can you try a hard refresh?

**Comment by jedwardwalters** [comment]
Ah, that did it. Thanks.

One other reminder on a thing I mentioned above: I changed the typo I made in the file name. So now instead of h21n1v1brock, it's h21v1brock.

The v1 and n1 are redundant for our purposes--I don't know what I was thinking when I did that the first time :)

**Comment by wsalesky** [comment]
Great, can we close this one? (Also, I opened a new issue to deal with filenames and user friendly URLs, will get to that next week.)

**Comment by jedwardwalters** [comment]
Yep. Closing now. Thanks!
