### ISSUE TITLE
Font appearance issues

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#25]
@wsalesky For things like italics, bold, etc. in display, should I just use the hi tag with rend="italic" (or "bold") in the XML document? Would that be the easiest way to catch those for CSS purposes?

**Comment by wsalesky** [comment]
@jedwardwalters yes hi tag with rend attribute will work out of the box, so to speak. The XSLT should catch the rend attribute, let me know if you notice things not rendering correctly after you encode them, the XSLT may be missing a few references.

**Comment by jedwardwalters** [comment]
Great! Thanks. I'm pretty sure the Ox Garage conversion from Word to TEI will catch all of the italics words and tag them automatically. But since I did this first article manually, I'll have to go back through. I'll leave this issue open until I do that.

**Comment by jedwardwalters** [comment]
Closing this.
