### ISSUE TITLE
Code Pretty URLs for users to get to articles and issues. 

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#26]

**Comment by wsalesky** [comment]
@jedwardwalters any chance we can change the uri's slightly? 
ex: `https://hugoye.org/h21v1n1brock`

to: `https://hugoye.org/article/h21v1n1brock`

It does not have to be 'article' but that extra content in the URL is going to make it easier for me to code the 'pretty' URLs.

**Comment by jedwardwalters** [comment]
This is fine with me. Should we use this as a way to distinguish between different kinds of materials? That is:
/article/ = articles
/review/ = book review
/report/ = conference report
/bibliography/ = bibliography
/memoriam/ = obituary/memoriam

Thoughts?

**Comment by wsalesky** [comment]
Sure. That works for me.

**Comment by jedwardwalters** [comment]
Great. By the way. I'm working on a second article for testing. My goal is to have the whole current issue to you (articles, reviews, etc) some time this month.
