### ISSUE TITLE
Index page description

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#3]
a. expand "Beth Mardutho" to "Beth Mardutho: The Syriac Institute" and link it to http://www.bethmardutho.org (with a target on a new tab)

b. Second paragraph, in "the root hg' meaning" replace the single quote with Unicode character 02BE.

**Comment by jedwardwalters** [comment]
My affiliation needs to be changed from Princeton Theological Seminary to Rochester College.

@wsalesky For small tweaks like this, I'm happy to make the changes myself, but I don't want to mess anything up. How do you feel about me making these kinds of changes? Would you prefer to keep control over that?

**Comment by wsalesky** [comment]
@jedwardwalters please go ahead and make the changes, that would be helpful. You won't mess anything up (just make sure the HTML is well formed, no broken or unclosed tags). Thanks.

**Comment by jedwardwalters** [comment]
Great! I'm happy to take some of the smaller things off your plate whenever I can!

**Comment by jedwardwalters** [comment]
Done.
