### ISSUE TITLE
Editors and Editorial Board Page 

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-app#4]
George Anton Kiraz, Beth Mardutho: The Syriac Institute

Associate Editor
J. Edward Walters, Rochester College

Book Review Editor
Ute Possekel, Harvard Divinity School

2) Create a separate editorial board page
List of board can be copied from here:
 http://www.bethmardutho.org/index.php/hugoye/editorial-board.html

**Comment by jedwardwalters** [comment]
I think we can close this now.
