### ISSUE TITLE
Italics in Book Titles

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#46]
Our book review editor has asked if there's a way that the book titles of the books being reviewed can be italicized on the volume pages (for example):
https://hugoye.bethmardutho.org/volume/22
https://hugoye.bethmardutho.org/current-issue.html
<img width="567" alt="Screen Shot 2019-09-05 at 10 35 33 PM" src="https://user-images.githubusercontent.com/11543800/64397096-00159c00-d02e-11e9-92c2-b307819e13c0.png">

And at the top of the individual pages of the reviews:
https://hugoye.bethmardutho.org/review/hv22n2prwalters
<img width="567" alt="Screen Shot 2019-09-05 at 10 35 50 PM" src="https://user-images.githubusercontent.com/11543800/64397099-03108c80-d02e-11e9-9d4c-8f86cebd50d4.png">

**Comment by jedwardwalters** [comment]
I looked around a bit, but I couldn't figure out where to do this myself. If you point me in the right direction I may be able to figure it out.

**Comment by wsalesky** [comment]
You would need to add the italics to the tei:title element in the tei:teiHeader

**Comment by jedwardwalters** [comment]
Oh okay. That's super simple then. I was assuming we'd have to re-do something in the CSS. I'll do a test case later.

**Comment by jedwardwalters** [comment]
Yep, that does it. Thank you!
