### ISSUE TITLE
Footnote display

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#56]
@wsalesky There's an issue with how footnote numbers get displayed when they're on a title that gets marked as a `<head>`. 

If you include the `<note>` tag within the `<head>` tag, then the text of the footnote shows up in the Table of Contents. That's easy to fix: I just move the note outside the `<head>` tag. But that creates a different problem: it makes the footnote number in the displayed text show up on a new line after the header title. See images below (the footnote number 23 is stranded on its own line):
<img width="799" alt="Screen Shot 2021-02-23 at 9 43 34 PM" src="https://user-images.githubusercontent.com/11543800/108939998-a1c4ea80-7620-11eb-95ce-5189f24a44e9.png">
<img width="662" alt="Screen Shot 2021-02-23 at 9 43 51 PM" src="https://user-images.githubusercontent.com/11543800/108939999-a1c4ea80-7620-11eb-9b33-b24854b1fed2.png">

By the way, this is in this review: https://hugoye.bethmardutho.org/article/hv24n1prpalmer

**Comment by wsalesky** [comment]
@jedwardwalters I think the correct solution is to filter the footnote out of the TOC display, so put it back in the head, and I will adjust the TOC code to not display the footnote.

**Comment by jedwardwalters** [comment]
@wsalesky That works for me!

**Comment by wsalesky** [comment]
Okay, the fix is up. Please let me know if it does not work as expected.

**Comment by jedwardwalters** [comment]
This worked great, by the way. Thanks.
