### ISSUE TITLE
Period placement after Syriac paragraph

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#57]
Also in the same review as the previous issue: https://hugoye.bethmardutho.org/article/hv24n1prpalmer

The period at the end of a Syriac quote paragraph is showing up on the right side of the final line, but it should be at the end on the left side. Any thoughts on how to fix this?
<img width="662" alt="Screen Shot 2021-02-23 at 10 07 26 PM" src="https://user-images.githubusercontent.com/11543800/108941873-d8503480-7623-11eb-908a-96ebbc8ad6e2.png">

**Comment by jedwardwalters** [comment]
I still can't quite get this period to place correctly. I tried a couple different things in the xml, but nothing got it to the end of the last word. Here's the closest it came (which is live now): [note the period is to the right of the final word, but it should be on the left]
![Screen Shot 2021-02-26 at 2 50 21 PM](https://user-images.githubusercontent.com/11543800/109348206-38bcbd00-7842-11eb-9df0-d4560734e803.png)
![Screen Shot 2021-02-26 at 2 50 35 PM](https://user-images.githubusercontent.com/11543800/109348208-39555380-7842-11eb-98ae-f357d9fc9389.png)

**Comment by wsalesky** [comment]
Fixed. Sorry, looks like webhooks never pulled that fix.

**Comment by jedwardwalters** [comment]
Thank you!
