### ISSUE TITLE
Subtitles not appearing on Index pages

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-app#61]
@wsalesky I feel like maybe we had this issue once previously, but maybe not. In the XML file structure, we have <title type="main"> and <title type="sub">. When present in the XML files, the latter (sub title) is not appearing on the index pages (i.e. for "Volume 24" or "Current Issue").

It should appear as [Title]: [Sub-title] (with a colon and space between)

**Comment by jedwardwalters** [comment]
See for example:

![Screen Shot 2021-09-23 at 2 09 23 PM](https://user-images.githubusercontent.com/11543800/134560962-8880799d-0ff9-48a0-a962-c408bd573db2.png)
![Screen Shot 2021-09-23 at 2 09 38 PM](https://user-images.githubusercontent.com/11543800/134560968-8a8dcd30-0676-4b89-8f6b-5f01646a6b3e.png)

**Comment by wsalesky** [comment]
link to the problematic record?

**Comment by jedwardwalters** [comment]
Data file: https://github.com/Beth-Mardutho/hugoye-data/blob/master/data/tei/HV24N2Pettipiece.xml

Index page: https://hugoye.bethmardutho.org/volume/24

**Comment by wsalesky** [comment]
Fixed. For some reason it was correct on github but not on the server.
